version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: schoolsync_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=patoniato
    ports:
      - '5433:5432'
    volumes:
      - schoolsync_db:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  #schoolsync:
  #  build: .
  #  ports:
  #  - "8081:8080"
  #  depends_on: [db,pgadmin]

volumes:
  schoolsync_db:
  #pgadmin-data:


