version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4    
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: patoniato
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
