# .github/workflows/build.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Nota: Reemplazar "main, master" con las branches principales que se manejen (ej.: "main, develop")
  push:
    branches:
      - 'main'
      - 'dev'
    pull_request:
      - 'main'
      - 'dev'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: runOnGitHub

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.10.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: List files
        run: |
          ls -la .github

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/